<script setup lang="ts">
import { AlertTriangle, DoorOpen, Flame, PhoneCall, ShieldCheck, Wind } from 'lucide-vue-next'
const cards=[
  {title:'Al detectar un incendio',icon:Flame,items:['Aléjate de la fuente de peligro y prioriza tu seguridad.','Avisa a otras personas cercanas si puedes hacerlo sin exponerte.','Reporta la situación a los servicios de emergencia o mediante ALERTA cuando sea seguro.']},
  {title:'Durante una evacuación',icon:DoorOpen,items:['Sigue las rutas de evacuación señalizadas y las instrucciones del personal responsable.','No regreses por objetos personales.','Ayuda a personas vulnerables solo si puedes hacerlo sin aumentar el riesgo.']},
  {title:'Humo y visibilidad',icon:Wind,items:['Evita ingresar a espacios con humo denso.','Si la ruta está comprometida, busca una salida alternativa segura.','No utilices ascensores durante una evacuación por incendio.']},
  {title:'Después de reportar',icon:ShieldCheck,items:['Mantén libre el acceso para los equipos de respuesta.','No difundas información no confirmada.','Espera indicaciones oficiales antes de regresar al área afectada.']},
]
</script>
<template><div class="mx-auto max-w-5xl space-y-6"><section><p class="text-[10px] font-semibold uppercase tracking-[0.24em] text-orange-500">Ciudadano · Información general</p><h2 class="mt-2 text-2xl font-semibold text-slate-900">Instrucciones de emergencia</h2><p class="mt-2 max-w-3xl text-sm text-slate-600">Recomendaciones generales para la demostración. En una emergencia real, sigue siempre las instrucciones de las autoridades y los planes de evacuación del lugar.</p></section><div class="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div class="flex gap-3"><AlertTriangle class="mt-0.5 h-5 w-5 shrink-0 text-amber-700"/><p class="text-sm text-amber-900"><strong>Importante:</strong> esta sección no sustituye protocolos oficiales ni instrucciones de personal capacitado.</p></div></div><section class="grid gap-4 md:grid-cols-2"><article v-for="card in cards" :key="card.title" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f6efe7] text-orange-600"><component :is="card.icon" class="h-5 w-5"/></div><h3 class="mt-4 text-lg font-semibold text-slate-900">{{ card.title }}</h3><ul class="mt-3 space-y-2 text-sm leading-6 text-slate-600"><li v-for="item in card.items" :key="item" class="flex gap-2"><span class="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-orange-400"></span><span>{{ item }}</span></li></ul></article></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex gap-3"><PhoneCall class="mt-0.5 h-5 w-5 shrink-0 text-sky-800"/><div><h3 class="font-semibold text-slate-900">Contactos de emergencia</h3><p class="mt-1 text-sm text-slate-600">El sistema puede mostrar los números configurados por cada institución. Verifica siempre la información oficial vigente antes de utilizarla en producción.</p></div></div></section></div></template>
